name: Build and deploy

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Log in to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push image
      id: build
      run: |
        IMAGE=ghcr.io/${{ github.repository }}
        docker build -t $IMAGE:latest -t $IMAGE:${{ github.sha }} .
        docker push $IMAGE:latest
        docker push $IMAGE:${{ github.sha }}
        echo "image=$IMAGE:${{ github.sha }}" >> $GITHUB_OUTPUT

    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Update Container App
      run: |
        az containerapp update \
          --name ${{ secrets.AZURE_CONTAINERAPP_NAME }} \
          --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
          --image ${{ steps.build.outputs.image }}
